### PR TITLE
Add a script for building with babel

### PR DESCRIPTION
**Pull request by eapache**
cc @boourns

### CODE REVIEW

**Comment by boourns** [comment]
there's a `watch` version of this command we should add too as it's extremely useful when developing:

```
babel --watch src/ --out-dir build/
```

**Comment by eapache** [comment]
Watch script added too

**Comment by boourns** [comment]
does the watch script work? I tried once before and it segfaulted

**Comment by eapache** [comment]
works for me here

**Comment by boourns** [comment]
shipit

**Pull request merged**
